---
title: "The Stock Market and Rational Expectations"
author: "Manolis Chatzikonstantinou"
institute: "Georgetown University"
date: "`r Sys.Date()`"
output: 
  xaringan::moon_reader:
    seal: false
    css: [default,metropolis, metropolis-fonts,"mctheme.css"]
    lib_dir: libs
    nature:
      highlightLines: true
      countIncrementalSlides: false
      slideNumberFormat: '%current%' 
      ratio: '16:9'
---

class: center,middle,mctitle-slide 


# The Stock Market and Rational Expectations

## Manolis Chatzikonstantinou  

---

class: my-one-page-font

# What will you learn today?


1. Calculate the price of common stock.

2. Recognize the impact of new information on stock
prices.

3. Compare and contrast adaptive and rational
expectations.

---

class: my-one-page-font

# Price of Common Stock

- We use The One-Period Valuation Model:


$$
P_{0}=\frac{\operatorname{Div}_{1}}{\left(1+k_{e}\right)}+\frac{P_{1}}{\left(1+k_{e}\right)}
$$
$P_{0}=$ the current price of the stock
$D^{D i v_{1}}=$ the dividend paid at the end of year 1
$k_{e}=$ the required return on investment in equity
$P_{1}=$ the sale price of the stock at the end of the first period

---

class: my-one-page-font

# The Generalized Dividend Valuation Model:

The value of stock today is the present value of all future cash flows
$$
P_{0}=\frac{D_{1}}{\left(1+k_{e}\right)^{1}}+\frac{D_{2}}{\left(1+k_{e}\right)^{2}}+\ldots+\frac{D_{n}}{\left(1+k_{e}\right)^{n}}+\frac{P_{n}}{\left(1+k_{e}\right)^{n}}
$$

If $P_{n}$ is far in the future, it will not affect $P_{0}$
$$
P_{0}=\sum_{t=1}^{\infty} \frac{D_{t}}{\left(1+k_{e}\right)^{t}}
$$
The price of the stock is determined only by the present value of the future dividend stream

---

class: my-one-page-font

# The Gordon Growth Model


$$
P_{0}=\frac{D_{0}(1+g)}{\left(k_{e}-g\right)}=\frac{D_{1}}{\left(k_{e}-g\right)}
$$
$D_{0}=$ the most recent dividend paid
$g=$ the expected constant growth rate in dividends
$k_{e}=$ the required return on an investment in equity

- Dividends are assumed to continue growing at a constant rate
forever

The growth rate is assumed to be less than the required return
on equity

---

class: my-one-page-font

# Valuation

video by sunderam


---

# How the Market Sets Stock Prices (1 of 2)

The price is set by the buyer willing to pay the highest
price.

The market price will be set by the buyer who can take
best advantage of the asset.

Superior information about an asset can increase its
value by reducing its perceived risk.

Information is important for individuals to value each
asset.

When new information is released about a firm,
expectations and prices change.

Market participants constantly receive information and
revise their expectations, so stock prices change
frequently.

---

# Monetary Policy and Stock Prices

> Monetary policy can affect stock prices in two ways. First,
when the Fed lowers interest rates, the return on bonds
(an alternative asset to stocks) declines, and investors
are likely to accept a lower required rate of return on an
investment in equity. The resulting decline lowers the
denominator in the Gordon growth model (Equation 5)
and raises stock prices.

> Furthermore, a lowering of interest rates is likely to
stimulate the economy, so the growth rate in dividends, g,
is likely to be somewhat higher. This rise in g also causes
the denominator in Equation 5 to decrease, which also
leads to a rise in stock prices.


---

# The Coronavirus Stock
Market Crash of 2020

The spread of the coronavirus in February 2020 triggered
a stock market crash in which the Dow Jones Industrial
Average fell from a peak of 29,551 on February 12 to
18,561 on March 20, a decline of 37%.

The combination of expectations of a lower dividend
growth rate (g) and a higher required return on investment

in equity $\left(k_{e}\right)$

led to one of the steepest stock market

declines in U.S. history.

video

---

# The Theory of Rational Expectations 

Adaptive expectations:

Expectations are formed from past experience only.

Changes in expectations will occur slowly over time
as data changes.

However, people use more than just past data to
form their expectations and sometimes change their
expectations quickly.

Expectations will be identical to optimal forecasts using
all available information.

Even though a rational expectation equals the optimal
forecast using all available information, a prediction
based on it may not always be perfectly accurate.

It takes too much effort to make their expectation the
best guess possible.

The best guess will not be accurate because the
predictor is unaware of some relevant information.


---

# The Theory of Rational Expectations 

- Rationale Behind the Theory

The incentives for equating expectations with optimal
forecasts are especially strong in financial markets. In
these markets, people with better forecasts of the future
get rich.

The application of the theory of rational expectations to
financial markets (where it is called the efficient market
hypothesis or the theory of efficient capital markets) is
thus particularly useful.

- Implications of the Theory

If there is a change in the way a variable moves, the way
in which expectations of the variable are formed will
change as well.

Changes in the conduct of monetary policy (e.g.,
target the federal funds rate)

The forecast errors of expectations will, on average, be
zero and cannot be predicted ahead of time.

---

# Take Home


__Useful Links:__
- [Data on budget deficits](http://www.cbo.gov/)
- [Financial Data](https://finance.yahoo.com/)
- [Get Financial Data in R](https://www.youtube.com/watch?v=hZS31_nSlGg)
