---
title: "The Efficient Market Hypothesis"
author: "Manolis Chatzikonstantinou"
institute: "Georgetown University"
date: "`r Sys.Date()`"
output: 
  xaringan::moon_reader:
    seal: false
    css: [default,metropolis, metropolis-fonts,"mctheme.css"]
    lib_dir: libs
    nature:
      highlightLines: true
      countIncrementalSlides: false
      slideNumberFormat: '%current%' 
      ratio: '16:9'
---

class: center,middle,mctitle-slide 


# The Efficient Market Hypothesis

## Manolis Chatzikonstantinou  

---


class: my-one-page-font

# What will you learn today?

2. Recognize the impact of new information on stock
prices.

3. Compare and contrast adaptive and rational
expectations.

1. Explain why arbitrage opportunities imply that the
efficient market hypothesis holds.

2. R7.5 Identify and explain the implications of the efficient
market hypothesis for financial markets.

7.6 Summarize the reasons why behavioral finance
suggestions that the efficient market hypothesis may not
hold.

---

class: my-one-page-font

# Recall

The rate of return from holding a security equals the sum of the capital
gain on the security, plus any cash payments divided by the initial
purchase price of the security.


$$
R=\frac{P_{t+1}-P_{t}+C}{P_{t}}
$$
$R=$ the rate of return on the security
$P_{t+1}=$ price of the security at time $t+1$, the end of the holding period
$P_{t}=$ price of the security at time $t$, the beginning of the holding period
$C=$ cash payment (coupon or dividend) made during the holding period

---

# The Theory of Rational Expectations 

Adaptive expectations:

Expectations are formed from past experience only.

Changes in expectations will occur slowly over time
as data changes.

However, people use more than just past data to
form their expectations and sometimes change their
expectations quickly.

Expectations will be identical to optimal forecasts using
all available information.

Even though a rational expectation equals the optimal
forecast using all available information, a prediction
based on it may not always be perfectly accurate.

It takes too much effort to make their expectation the
best guess possible.

The best guess will not be accurate because the
predictor is unaware of some relevant information.


---

# The Theory of Rational Expectations 

- Rationale Behind the Theory

The incentives for equating expectations with optimal
forecasts are especially strong in financial markets. In
these markets, people with better forecasts of the future
get rich.

The application of the theory of rational expectations to
financial markets (where it is called the efficient market
hypothesis or the theory of efficient capital markets) is
thus particularly useful.

- Implications of the Theory

If there is a change in the way a variable moves, the way
in which expectations of the variable are formed will
change as well.

Changes in the conduct of monetary policy (e.g.,
target the federal funds rate)

The forecast errors of expectations will, on average, be
zero and cannot be predicted ahead of time.

---

class: my-one-page-font

# Forming Expectations

At the beginning of the period, we know $P_{t}$ and $C$. $P_{t+1}$ is unknown and we must form an expectation of it. The expected return then is
$$
R^{e}=\frac{P_{t+1}^{e}-P_{t}+C}{P_{t}}
$$


Expectations of future prices are equal to optimal forecasts using all currently available information so
$$
P_{t+1}^{e}=P_{t+1}^{o f} \Rightarrow R^{e}=R^{\circ f}
$$

- But returns can not be far away from equilibrium returns: 

$$
R^{\text {of }}=R^{e}=R^{*}
$$

---

# The Efficient Market Hypothesis

- Rational Expectations in Financial Markets


Current prices in a financial market will be set so that the
optimal forecast of a security’s return using all available
information equals the security’s equilibrium return.

In an efficient market, a security’s price fully reflects all
available information.

- In an efficient market, all unexploited profit opportunities will
be eliminated

- Why does this imply $R^{\text {of }}=R^{e}=R^{*}$?

$$
\begin{aligned}
&R^{\text {of }}>R^{*} \Rightarrow P_{t} \uparrow \Rightarrow R^{\circ f} \downarrow \\
&R^{\circ f}<R^{*} \Rightarrow P_{t} \downarrow \Rightarrow R^{\circ o f} \uparrow
\end{aligned}
$$
until
$$
R^{\circ f}=R^{\star}
$$

---

# Application

How Valuable Are Published Reports by
Investment Advisors?

Information in newspapers and in the published reports of
investment advisers is readily available to many market
participants and is already reflected in market prices.

Acting on this information will not yield abnormally high
returns, on average.

The empirical evidence for the most part confirms that
recommendations from investment advisers cannot help
us outperform the general market.

Recommendations from investment advisors cannot help
us outperform the market.

A hot tip is probably information already contained in the
price of the stock.

Stock prices respond to announcements only when the
information is new and unexpected.

A “buy and hold” strategy is the most sensible strategy for
the small investor.


---

# Application

Application: What Do Stock Market Crashes Tell Us
About the Efficient Market Hypothesis and the Efficiency
of Financial Markets?

Nothing in efficient markets theory rules out large changes
in stock prices. A large change in stock prices can result
from new information that produces a dramatic decline in
optimal forecasts of the future valuation of firms. However,
economists are hard pressed to find fundamental changes
in the economy that would have caused the Black Monday
and tech crashes. One lesson from these crashes is that
factors other than market fundamentals may have an effect
on asset prices.

Why the Efficient Market Hypothesis Does Not
Imply That Financial Markets Are Efficient

Some financial economists believe all prices are always
correct and reflect market fundamentals (items that
have a direct impact on future income streams of the
securities) and so financial markets are efficient.

However, prices in markets like the stock market are
unpredictable. This casts serious doubt on the stronger
view that financial markets are efficient.

---

# Benchmarks for Stock Prices