---
title: "Unemployment and its causes"
author: "Manolis Chatzikonstantinou"
institute: "Georgetown University"
date: "`r Sys.Date()`"
output: 
  xaringan::moon_reader:
    seal: false
    css: [default,metropolis, metropolis-fonts,"mctheme.css"]
    lib_dir: libs
    nature:
      highlightLines: true
      countIncrementalSlides: false
      slideNumberFormat: '%current%' 
      ratio: '16:9'
---

class: center,middle,mctitle-slide 


# Unemployment and Inflation

## Manolis Chatzikonstantinou  

---


# What will you learn this week?


How is unemployment measured and how is the
unemployment rate calculated?
--
What is the significance of the unemployment rate for the
economy?
--
What is the relationship between the unemployment rate
and economic growth?
--
What factors determine the natural rate of
unemployment?
--
What are the economic costs of inflation?
--
How do inflation and deflation create winners and losers?
--
Why do policy makers try to maintain a stable rate of
inflation?

---

# The unemployment rate in the US, 1948-2020

Unemployment always rises during recessions and usually (but not always) falls during periods of economic expansion.

graph table code

---

#  Employment and Unemployment

  - Why Unemployment Is a Problem ?

Unemployment results in:

- Lost incomes and production

  - Lost income $\rightarrow$ reduction in demand and welfare
  - Employment benefits create a safety net $\rightarrow$ not fully and not for long

-- 

- Lost human capital

 - Prolonged unemployment permanently damages a
person’s job prospects by destroying human
capital.

http://www.bls.gov/eag/eag.us.htm

-- 

 - Is everyone not working, unemployed?

--

The working age population is divided into two groups:

1. People in the labor force
2. People not in the labor force

--

__The labor force is the sum of employed and unemployed workers.__

--

- Who is counted as unemployed ? 

---

# Labor Force Statistics

Employment: the total number of people currently employed, either full time or part time 
Unemployment: the total number of people who are actively looking for work but aren’t currently employed 
Labor force: the sum of employment and unemployment

- __Working age population__

--

Labor force participation rate: the percentage of adults (people 16 and older) in the labor force
Unemployment rate: the percent of the total number of people in the labor force who are unemployed

$$
\text { Labor force participation rate }=\frac{\text { Labor force }}{\text { Population age } 16 \text { and older }} \times 100
$$

$$
\text { Unemployment rate }=\frac{\text { Number of unemployed workers }}{\text { Labor force }} \times 100
$$

---

# Unemployment: Significance and Pitfalls

The unemployment rate is a good but imperfect indicator of how easy or difficult it is to find a job:

It can overstate the true level of unemployment.
It takes at least a few weeks to find a job. If you are searching for a job and have not yet found one, you are counted as unemployed. 
The unemployment rate never falls to zero, even in boom times when jobs are plentiful. 


It can understate the true level of unemployment.
Discouraged workers: those who have given up looking for a job because there are no jobs available. 
The deeper the recession, the more discouraged workers there are.
They are part of a larger group—marginally attached  workers: those who looked for work in the past (looked in the past 12 months but NOT in the past 4 weeks) but are not currently looking for work.
The underemployed: those who would like to work full time but are currently working part time.



So how good an indicator is the unemployment rate? 
It isn’t perfect.
It doesn’t measure the quality of jobs or how well people are matched to their jobs.
Economists also look at other indicators:
Labor force participation rate
Number of full-time jobs
Average wages


---

# Alternative measures of unemployment


The unemployment rate counts people as unemployed if they have been looking for work during the past four weeks. 
Broader measures also count discouraged workers, marginally attached workers, and the underemployed. 

altmeasures.png

---

# Unemployment rates and demographics

- Data show that unemployment rates vary greatly between
groups.


---

# Unemployment and growth

GROWTH AND CHANGES IN UNEMPLOYMENT,
1949 2016
•
Generally there is a negative relationship between
economic growth and the unemployment rate. A jobless
recovery is a period in which the real GDP growth rate is
positive but the unemployment rate is still rising

There is a generally strong negative relationship between growth and unemployment. 
The green vertical line indicates the average growth rate of real GDP. Points to the right of the green line: above-average growth and falling unemployment. 
Points to the left of the green line: below-average growth and usually rising unemployment. A period when the growth is below the average and unemployment is rising is called a jobless recovery or a growth recession. 

---

# Job Creation and destruction

If fast economic growth reduces the unemployment rate, how low can it go?
Over the past 50 years, the national unemployment rate has never dropped below 2.9%.
Even in the best of times, jobs are constantly being created and destroyed. 
There are three types of unemployment:
frictional
structural
cyclical

Even in low-employment months, many workers move into and out of both employment and unemployment.


---

# Frictional Unemployment
Frictional Unemployment
is unemployment that arises
from normal labor market turnover.
•
The creation and destruction of jobs requires that unemployed
workers search for new jobs.
•
Increases in the number of people entering and reentering the labor
force and increases in unemployment benefits raise frictional
unemployment.
•
Frictional unemployment is a permanent and healthy phenomenon of
a growing economy

--

__Duration:__ The short duration of unemployment for most workers suggests that unemployment in early 2020 was mostly frictional.

---

# Structural Unemployment

Sometimes there is a persistent surplus of job-seekers in a particular labor market:
There may be more workers with a particular skill than there are jobs available for that skill, or 
There may be more workers in a particular geographic region than there are jobs in that region.  

Structural unemployment: more people are seeking jobs in a particular labor market than there are jobs available at the current wage rate, even when the economy is at the peak of the business cycle.

Structural unemployment occurs when the wage rate is persistently above the equilibrium wage rate. 
Several factors can lead to a wage rate in excess of the equilibrium wage rate:
Minimum wages
Unions
Efficiency wages
Side effects of government policies
Mismatches between employees and employers

---

# Micro Review: Minimum wages

A minimum wage is a government-mandated floor on the wage rate.
A binding minimum wage leads to a persistent surplus in the labor market.
A sufficiently high minimum wage leads to structural unemployment. 
The minimum wage in the United States is quite low and isn’t binding for the majority of workers. 

--

__Side effects:__ Benefits to laid-off workers reduce workers’ incentive to quickly find a new job. 
During the 1980s, generous unemployment benefits in some European countries contributed to Eurosclerosis, persistently high unemployment.

---

# Cyclical unemployment

Cyclical Unemployment is the higher than normal
unemployment at a business cycle trough and lower than
normal unemployment at a business cycle peak.
•
A worker laid off because the economy is in a
recession and is then rehired when the expansion
begins experiences cycle unemployment.

“
Natural” Unemployment is the unemployment that arises
from frictions and structural change when there is no cyclical
unemployment.
•
Frictional and structural unemployment are always present;
they are “natural.”
•
Natural unemployment frictional unemployment +
structural unemployment
•
Actual unemployment = natural unemployment + cyclical
unemployment

--

It takes time for workers and firms to adjust to shifts in the economy. 
The result can be a mismatch between what employees have to offer and what employers are looking for. 
A skills mismatch
A geographic mismatch


---

# Unemployment and full employment

The natural unemployment rate changes over time and is
influenced by many factors.
•
We need estimates of the natural rate of unemployment both to make forecasts and to conduct policy analyses.
What causes it to change?
Changes in characteristics of the labor force
Changing demographics
Changes in labor market institutions
Unions, temp agencies, and new technology
Changes in government policies
Job-training programs

--

Real GDP and Unemployment Over the Cycle
Potential GDP is the quantity of real GDP produced at full
employment.
Potential GDP corresponds to the capacity of the economy to
produce output on a sustained basis.
Real GDP minus potential GDP is the output gap.
Over the business cycle, the output gap fluctuates and the
unemployment rate fluctuates around the natural unemployment rate.



---

# What we learned?


__Useful Links__

- tradingeconomics

-

http://www.bls.gov/eag/eag.us.htm
https://www.statista.com/statistics/808890/unemployment-rate-in-qatar/

https://www.imf.org/external/datamapper/LUR@WEO/OEMDC/ADVEC/WEOWORLD

https://www.bls.gov/cps/lfcharacteristics.htm#unemp

