---
title: "Recitation 2"
author: "Manolis Chatzikonstantinou"
date: "1/13/2022"
output:
  word_document: default
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Price Indexes and the Aggregate Price Level 
A.	The aggregate price level is a measure of the overall level of prices in the economy. A hypothetical consumption bundle, used to measure changes in the overall price level, is known as a market basket.
B.	A price index measures the cost of purchasing a given market basket in a given year, where that cost is normalized so that it is equal to 100 in the selected base year. 

C.	Formula for price index: 

$$\text { Price index in a given year }=\frac{\text { Cost of market basket in a given year }}{\text { Cost of market basket in base year }} 100$$

D.	The inflation rate is the percent change per year in a price index—typically, the consumer price index. 
E.	The inflation rate from year 1 to year 2 is computed as: 

$$
\text { Inflation rate }=\frac{\text { Price index in year } 2-\text { Price index in year } 1}{\text { Price index in year } 1} 100
$$

F.	There are three measures of prices in the macroeconomy: 
-	the consumer price index, or CPI, which measures the cost of the market basket of a typical urban U.S. family. 
-	the producer price index, or PPI, which measures changes in the prices of goods purchased by producers. 
-	the GDP deflator, which is 100 times the ratio of nominal GDP to real GDP in that year.
-	The most important point about the different inflation rates is that they usually move closely together.


## Question:

Suppose that people consume only three goods, as shown in this table :

|               | Tennis Balls | Golf Balls | Gatorade |
|:-------------:|:------------:|:----------:|:--------:|
|  2017 Price   |     \$2      |    \$4     |   \$1    |
| 2017 Quantity |     100      |    100     |   200    |
|  2018 Price   |     \$2      |    \$6     |   \$2    |
| 2018 Quantity |     100      |    100     |   200    |

1.  What is the percentage change in the price of each of the three goods?

2.  Using a method similar to the CPI, compute the percentage change in the overall price level. If you were to learn that a bottle of Gatorade increased in size from 2017 to 2018, should that information affect your calculation of the inflation rate? If so, how?

**Answers:**

  1.  The percentage change in the price of each of the three goods:

        -   Tennis Balls : 0 %

        -   Golf Balls : 50 %

        -   Gatorade : 100 %

  2.  Here, since in the two years people are consuming the same amount of goods, the total amount of goods consumed can serve as the basket of goods for CPI:

        -   Total Cost in \$ {2017}=100 $\times$ 2+100 $\times$ 4+ 200$\times$ 1= 800\$

        -   Total Cost in \$ {2018}=100 $\times$ 2+100 $\times$ 6+ 200$\times$ 2= 1200\$

            Therefore, CPI using 2017 as the Base year would be

        -   CPI in \$ {2017}= $\frac{\text { TotalCost }_{2017}}{\text { TotalCost }_{2017}} \times 100=100$

        -   CPI in \$ {2018}= $\frac{\text { TotalCost }_{2018}}{\text { TotalCost }_{2017}} \times 100=150$

            And the percentage change in the overall price level :

        -   \% change =$\frac{C P I_{2018}-C P I_{2017}}{C P I_{2017}} \times 100=50 \%$


If we find out that the size of a bottle of Gatorade had doubled in 2018 compared to 2017, then the increase in the price of Gatorade that we observe does not mean that Gatorade has become more expensive : it instead means that people consume more Gatorade than before. However, that effect is not taken into account when calculating Price level using CPI. Therefore compared to the inflation rate we get using CPI, the real inflation rate should be smaller.
    
    
## The Unemployment Rate 
A.	Defining and measuring unemployment 
  1.	Employment is the number of people currently employed in the economy, either full time or part time. 
  2.	Unemployment is the number of people who are actively looking for work but aren’t currently employed. 
  3.	The labor force is equal to the sum of employment and unemployment. 
  4.	The labor force participation rate is the percentage of the population 16 or older that is in the labor force. 
  5.	The unemployment rate is the percentage of the total number of people in the labor force who are unemployed. 


### Question 1:

Calculate the Unemployment Rate in the following case:

- Number of people employed	120,500
- Number of people unemployed	4,050
- (Working Age) Population	367,000

Given the above data, compute:

1.	The number of people in the labor force
2.	The labor force participation rate
3.	The unemployment rate 

__Answer__:

1. The number of people in the labor force: $4,050+120,500=124,550$
2. The labor force participation rate: $124,550 / 367,000=33.94 \%$
3. The unemployment rate: $(4,050 /(4,050+120,500) \times 100)=3.25 \%$


## The Natural Rate of Unemployment 

A.	Job creation and job destruction 
  1.	Jobs are constantly being created and destroyed. Structural change can be responsible for job losses and new jobs created. Poor performance at individual companies also leads to job loss for their employees. 
  2.	Continual job creation and job destruction make a naturally occurring amount of unemployment inevitable. There are two types of naturally occurring unemployment—frictional and structural. 
B.	Frictional unemployment 
  -	Frictional unemployment is unemployment due to the time workers spend in search of a job. 
C.	Structural unemployment 
  1.	In structural unemployment, more people are seeking jobs in a particular labor market than there are jobs available at the current wage rate, even when the economy is at the peak of the business cycle. 
  2.	Structural unemployment occurs when the wage rate is persistently above the equilibrium level.  
  3.	Several factors can lead to a wage rate in excess of the equilibrium wage rate: minimum wages, unions, efficiency wages, side effects of government policies, and mismatches between employees and employers.
  
### Question 2:


Classify the people described in each of the following scenarios as either frictionally, structurally, or cyclically unemployed.

1.	Phil is currently unemployed because the tire factory where he used to work installed robots, which replaced 500 laborers, including Phil. 

2.	Jessica is unemployed because she is in the process of reentering the labor force after taking time off to have a baby. 

3.	Mary is unemployed because she lost her job at McDonald’s after the state increased the minimum wage. 

4.	Barry is unemployed because he was laid off by the automobile factory when the economy entered a severe, prolonged recession. 

5.	Sandy left her former job at an accounting firm a month ago. She is in the process of interviewing for a similar position at six different accounting firms, although she has not yet accepted a job. 



__Answer__:

Name the Type of Unemployment

1.	Phil is structurally unemployed. 

2.  Jessica is frictionally unemployed. 

3.	Mary is structurally unemployed. 

4.	Barry is cyclically unemployed. 

5.	Sandy is frictionally unemployed.




### Question 3:

Compute the answers to the following questions. 
1.	Samantha invested $2,500 of her savings in a certificate of deposit that pays an annual 4.25% rate of interest. The current annual inflation rate is 5%. Will Samantha be better financially that she is today, based
on the return of the bond?

2.	William wants to earn a real annual interest rate on his investment of at least 7%. If the annual rate of inflation is 4%, what is the minimum nominal rate of interest William would be willing to accept on his investment? 

__Answer__

1.
The return of the bond is the real interest rate (in terms of purchasing power). The real interest rate she is earning on this investment is negative. The real interest rate Samantha is earning is computed as follows:
Real interest rate $=$ Nominal interest rate $-$ Rate of inflation
Real interest rate $=4.25 \%-5 \%=-0.75 \%$

2.
William must receive a minimum nominal annual rate of interest equal to $11 \%$, which is computed as follows: Real interest rate $=$ Nominal interest rate $-$ Rate of inflation
$7 \%=$ Nominal interest rate $-4 \%$
Nominal interest rate $=11 \%$


### Question 4:

The accompanying table contains two price indexes for the years 2016, 2017, and 2018: the GDP deflator and the CPI. For each price index, calculate the inflation rate from 2016 to 2017 and from 2017 to 2018.

| Year | GDP deflator | CPI |
| :--- | :--- | :--- |
| 2016 | 106.551 | 241.432 |
| 2017 | 108.713 | 246.524 |
| 2018 | 111.256 | 251.233 |

The accompanying table calculates the inflation rates based on the GDP deflator and on the CPI:

|  |  | Inflation |  | Inflation |
| :---: | :---: | :---: | :---: | :---: |
| Year | deflator | deflator) | CPI | CPI) |
| 2016 | 106.551 |  | 241.432 |  |
| 2017 | 108.713 | 2.03% | 246.524 | 2.11% |
| 2018 | 111.256 | 2.34% | 251.233 | 1.91% |
