---
title: "Recitation 1"
author: "Manolis Chatzikonstantinou"
date: "1/6/2022"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

-   Definition of GDP

    "GDP is the market value of all final goods and services produced within a country in a given period of time"

    It does not include the value of intermediate goods. Consider the following example:

    " A farmer grows wheat, which she sells to a miller for $\$ 100$. The miller turns the wheat into flour, which she sells to a baker for $\$ 150$. The baker turns the wheat into bread, which she sells to consumers for $\$ 180$. Consumers eat the bread. We can measure the contribution to GDP as the value of consumption, which is $\$ 180$ or as the sum of all value added: 100 from growing wheat is the value added by the first producer, 50 from transforming it to flour and 30 from turning it to bread.

    -   Limitations of GDP

        -   Does not account for home production. It overestimates the gap between developed countries and developing countries, or countries with different culture (US vs. India). For example, goods and services that are not sold in markets, such as food produced consumed at home, are generally not included in GDP

        <!-- -->

        -   It is a measure of production not happiness. For example, productive activities that contribute a lot to increased pollution are counted the same way as those that do not.It is a measure of production not wealth. For example, as a measure of production could go up after a disaster since the reconstruction process would lead to increased production

    -   Examples: **Included in GDP** or Not Included in GDP?

        **1. A restaurant makes a sandwich to sell to a customer**

        2\. You make yourself a sandwich

        3\. A pizza shop buys tomatoes to use to make pizza

        **4. A pizza shop buys an oven to use to make pizza**

        5\. Toyota produces a car in Japan that is sold in the US

        **6. Ford produces a car in the US that is sold in Japan**

        **7. A house is built and sold this year**

        8\. A house is built in 1995 and sold this year

## Question 1

Consider an Economy that produces only chocolate bars. In year 1 , they produce 3 bars at $\$ 4$ each, in year 2 , 4 bars at $\$ 5$, and in year 3, 5 bars at $\$ 6$. Year 1 is base year.

1.  What is nominal GDP for each year? Is this correctly calculated from revenue or expenditures?

2.  What is real GDP for each of these years?

3.  What is GDP deflator for each of these years?

4.  What is the percentage growth rate of real GDP from year 2 to $3 .$

5.  What is the inflation rate, as measured by GDP deflator from year 2 to 3 .

6.  Can you answer (e) and (e) without (b) and (c) (Hint, there's only one good)

**Answers**

1.  The value of nominal GDP is the market value of final goods, so we sum the value of goods produced (value = price per unit $\times$ quantity)

    So we have in year 1: $\$ 12$ ,in year 2 \$ 20, and in year 3: $\$ 30$.

2.  The value of real GDP is the market value of final goods where the prices of the good is the same as the base year (value = price per unit in base year $\times$ quantity)

    So we have in year 1: $\$ 12$ ,in year 2 \$ 16, and in year 3: $\$ 20$.

3.  The GDP deflator is calculated as the ratio of nominal to real GDP, since it the correction we do to account for the different prices

    So we have in year 1: 12/12 $\times$ 100 = 100 , in year 2 , 20/16 $\times$ 100 = 125 and in year 3 : 30/20 $\times$ 100 = 150

<!-- -->

4.  The growth in real GDP is calculated as the percentage change in two consecutive years, so we have that the percentage growth rate of real GDP from year 2 to $3 .(20-16) / 16 \times 100=25 \%$

5.  The inflation rate, as measured by GDP deflator from year 2 to 3 is:$(150-125) / 125 \times 100=20 \%$

6.  Yes, inflation can be measured with just price changes. This comes from the fact that there is only one good. Two or more goods, this is no longer true.

## Question 2

Calculating Nominal GDP, Real GDP, GDP growth rate, GDP Deflator and Inflation

| Year | Milk (P) |  Milk (Q)  | Honey (P) | Honey (Q)  |
|:----:|:--------:|:----------:|:---------:|:----------:|
| 2016 |   \$ 1   | 100 quarts |    \$2    | 50 quarts  |
| 2017 |   \$ 1   | 100 quarts |    \$2    | 100 quarts |
| 2018 |   \$ 2   | 100 quarts |    \$4    | 100 quarts |

**Answer:**

I choose the base year to be 2016:

| Year | NGPD = $\sum P \times Q$ |        RGDP        |      RGDP_gr       | GDP Defl.   | Inflation |
|------|:------------------------:|:------------------:|:------------------:|-------------|:---------:|
| 2016 |    1\*100+2\*50=\$200    | 1\*100+2\*50=\$200 |         \-         | 100         |    \-     |
| 2017 |    1\*100+2\*100=300     | 1\*100+2\*100=300  | (300-200)/200 = .5 | 100         |     0     |
| 2018 |    2\*100+4\*100=600     | 1\*100+2\*100=300  | (300-300)/300 = 0  | 600/3 = 200 |   100 %   |

## Question 3:

Suppose that people consume only three goods, as shown in this table :

|               | Tennis Balls | Golf Balls | Gatorade |
|:-------------:|:------------:|:----------:|:--------:|
|  2017 Price   |     \$2      |    \$4     |   \$1    |
| 2017 Quantity |     100      |    100     |   200    |
|  2018 Price   |     \$2      |    \$6     |   \$2    |
| 2018 Quantity |     100      |    100     |   200    |

1.  What is the percentage change in the price of each of the three goods?

2.  Using a method similar to the CPI, compute the percentage change in the overall price level. If you were to learn that a bottle of Gatorade increased in size from 2017 to 2018, should that information affect your calculation of the inflation rate? If so, how?

    **Answers:**

    1.  The percentage change in the price of each of the three goods:

        -   Tennis Balls : 0 %

        -   Golf Balls : 50 %

        -   Gatorade : 100 %

    2.  Here, since in the two years people are consuming the same amount of goods, the total amount of goods consumed can serve as the basket of goods for CPI:

        -   Total Cost in \$ {2017}=100 $\times$ 2+100 $\times$ 4+ 200$\times$ 1= 800\$

        -   Total Cost in \$ {2018}=100 $\times$ 2+100 $\times$ 6+ 200$\times$ 2= 120\$

            Therefore, CPI using 2017 as the Base year would be

        -   CPI in \$ {2017}= $\frac{\text { TotalCost }_{2017}}{\text { TotalCost }_{2017}} \times 100=100$

        -   CPI in \$ {2018}= $\frac{\text { TotalCost }_{2018}}{\text { TotalCost }_{2017}} \times 100=150$

            And the percentage change in the overall price level :

        -   \% change =$\frac{C P I_{2018}-C P I_{2017}}{C P I_{2017}} \times 100=50 \%$

    If we find out that the size of a bottle of Gatorade had doubled in 2018 compared to 2017, then the increase in the price of Gatorade that we observe does not mean that Gatorade has become more expensive : it instead means that people consume more Gatorade than before. However, that effect is not taken into account when calculating Price level using CPI. Therefore compared to the inflation rate we get using CPI, the real inflation rate should be smaller.

## Question 4: Hands on students

Ask the students to fill the following table

| Year | Real GDP (Base Year 2000) | Nominal GDP | Deflator | Real GDP Growth Percent |
|:-----|:--------------------------|:------------|:---------|:------------------------|
| 1970 | 3000                      | 1200        | ?        | \-                      |
| 1980 | 5000                      | ?           | 60       | ?                       |
| 1990 | ?                         | 6000        | 100      | ?                       |
| 2000 | ?                         | ?           | ?        | 5                       |

Answer

| Year | Real GDP (Base Year 2000) | Nominal GDP       | Deflator          | Real GDP Growth Percent |
|:-----|:--------------------------|:------------------|:------------------|:------------------------|
| 1970 | 3000                      | 1200              | 1200/3000\*100=40 | \-                      |
| 1980 | 5000                      | 5000\*60/100=3000 | 60                | (5000-3000)/(3000)      |
| 1990 | 6000                      | 6000              | 100               | (6000-5000)/(5000)      |
| 2000 | 6000 \* 1.05=6300         | 6300              | 100               | 5                       |

Steps:

1.  Deflator in 1970, ratio of nominal to real GDP.

2.  Nominal GDP in 1980, real GDP\*GDP deflator/100

3.  Real GDP growth in 1980 and 1990,

    $$\frac{\text{real GDP} -  \text{real GDP previous period}}{\text{real GDP previous period}} \times 100$$

4.  In year 2000, GDP deflator in 100 base year, when the GDP deflator is 100:

    Nominal GDP = Real GDP.

5.  In year 2000, real GDP = real GDP in 1990 \* (1+Growth/100)

    $$\text{real GDP} = ( \text{real GDP previous period})\times (1+ \text{real GDP Growth}/ 100)$$

## Short Exercises

49. The table below contains data for the country of Togogo. The base year is $1974 .$

| Year | Nominal GDP | GDP Deflator |
|:----:|:-----------:|:------------:|
| 1974 |   \$2000    |     100      |
| 1975 |   \$3000    |     120      |
| 1976 |   \$3750    |     150      |
| 1977 |   \$6000    |     200      |

From 1975 to 1976,

<!-- -->

a.  Inflation was $25 \%$ and output did not grow.
b.  Inflation was $25 \%$ and output grew.
c.  Inflation was $50 \%$ and output did not grow.
d.  Inflation was $50 \%$ and output grew.

<!-- -->

65. For an imaginary economy, the consumer price index was 80 in 2014, 100 in 2015, and 140 in 2016. Which of the following statements is correct?

<!-- -->

a.  If the basket of goods that is used to calculate the CPI cost \$40 in 2014, then that basket of goods cost \$60 in 2015.
b.  If the basket of goods that is used to calculate the CPI cost \$25 in 2015, then that basket of goods cost \$35 in 2016.
c.  The overall level of prices increased by 60 percent between 2014 and 2016.
d.  All of the above are correct
