---
title: "Review 1"
author: "Manolis Chatzikonstantinou"
date: "1/6/2022"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

# Chapter 6 Outline

## The Nature of Macroeconomics

**Microeconomics** focuses on decisions made by individuals and firms. \_\_Macroeconomics\_\_focuses on the behavior of the economy as a whole. Macroeconomic questions can't be answered simply by adding up microeconomic answers because macroeconomics is more than the sum of its parts. The combined effect of individual decisions can have results that are very different from what any one individual intends. The paradox of thrift is an example.

### Macroeconomics: Theory and policy

1.    Before the 1930s, economists tended to believe that the economy was self-regulating, problems such as unemployment resolve without government intervention, through the workings of the "invisible hand." Government interventions would probably make things worse. 

2. The Great Depression changed all that. According to Keynesian economics, economic slumps are caused by inadequate spending, and government intervention can mitigate the slump. 

3. Keynes argued that government intervention can help a depressed economy through monetary policy and fiscal policy. Monetary policy uses changes in the quantity of money to alter interest rates, which in turn affect the level of overall spending. Fiscal policy uses changes in taxes and government spending to affect overall spending.

### The Business Cycle

1.    Over time, major economic indicators increase, but it's not a steady upward trend: In the early 1990s, the early 2000s, 2007, and 2020, both employment and industrial output stumbled. The uneven pace of the economy's progress is one of the main preoccupations of macroeconomics. 

2.    The business cycle is made up of recessions (also called contractions), which are periods of economic downturn when output and employment are falling, and expansions (also called recoveries), which are periods of economic upturn when output and employment are rising. 

3.    The business-cycle peak is the point in time at which the economy shifts from expansion to recession. 

4.    The business-cycle trough is the point in time at which the economy shifts from recession to expansion. 

5.    The pain of recession is felt by workers who are unable to find or hold jobs. Because recessions cause many people to lose their jobs and make it hard to find new ones, they reduce the standard of living across the country.

### Taming the business cycle

1.    Modern macroeconomics largely came into being as a response to the recession of 1929--1933 that ushered the Great Depression. 

2.    John Maynard Keynes suggested that policy makers should use monetary and fiscal policies to mitigate the effects of recessions, and Milton Friedman argued that it's important to rein in booms as well as to fight slumps. 

3.    Although fiscal and monetary policies haven't been completely successful, they have helped make the economy more stable.

### Long-Run Economic Growth

1.    Long-run economic growth is the sustained rise in the quantity of goods and services the economy produces. fundamental to many of the most pressing economic questions of the day. 

2.    Long-run growth per capita --- a sustained upward trend in output per person --- is the key to higher wages and a rising standard of living. 

3.    Long-run economic growth is a modern invention: Britain, for example, wasn't any richer in 1650 than it was two centuries earlier. Countries don't grow at the same rate. For example, Britain was much richer than the United States, but the United States grew faster after 1875. 

4.    Macroeconomists do not use the same models to think about long-run growth as they use to think about the business cycle.

### Inflation and Deflation

1.    A rising level of prices is inflation. A falling level of prices is deflation. 

2.    In the short run, movements in inflation are closely related to the business cycle. When the economy is depressed, inflation tends to fall; when the economy is booming, inflation tends to rise. 

3.    In the long run, the overall level of prices is mainly determined by changes in the money supply. 

4.    The pain of inflation and deflation: inflation discourages people from holding onto cash, because cash loses value over time; deflation can cause the reverse problem when holding on to cash is more attractive than investing in productive assets which can deepen a recession. 

5.    Price stability is the situation when the overall level of prices changes slowly. Price stability is a desirable goal, and from the 1990s to the present, it has been achieved.

# Chapter 7 outline

## The National Accounts 
A.	In the United States, the Bureau of Economic Analysis—a division of the Commerce Department—collects and calculates various types of economic data and compiles them in the national income and product accounts. 
B.	The national income and product accounts, or national accounts, keep track of the flow of money between different sectors of the economy. 
C.	The expanded circular flow diagram, shown in Figure 7(22)-1 in the text (and reproduced above), illustrates the flow of funds through the four sectors of the economy—households, firms, government, and the rest of the world—via three types of markets—factor markets, markets for goods and services, and financial markets. 
D.	Households 
    1.	Consumer spending is household spending on goods and services. 
    2.	Most households receive the majority of their income from wages. However, some households also receive    income from the ownership of stocks and bonds, which generate profit and interest income, respectively. 
    3.	The total amount available to households for consumption and saving is disposable income, equal to income plus government transfers minus taxes. 
    4.	Private savings, equal to disposable income minus consumer spending, is disposable income that is not spent on consumption. 
    5.	The total sum of flows of money out of households—the sum of taxes paid, consumer spending, and private savings—must equal the total flow of money into households—the sum of wages, profits, interest, rent, and government transfers. 
E.	Financial markets
  1.	The banking, stock, and bond markets, which channel private savings and foreign lending into investment spending, government borrowing, and foreign borrowing, are known as the financial markets. 
F.	Government 
  1.	Government borrowing is the amount of funds borrowed by federal, state, and local governments in the financial markets. 
  2. Government purchases of goods and services are total expenditures on goods and services by federal, state, and local governments. 
G.	International sector 
  1.	The international sector is involved in the economy through exports and imports. 
H.	Business investment 
  1.	Investment spending is spending on productive physical capital, such as machinery and construction of structures, and on changes to inventories. 


##	Gross domestic product 

1.	If we add up consumer spending, investment spending, government purchases, exports and subtract imports, we will get the market value of the goods and services the economy produces—the country’s gross domestic product. 
2.	Goods and services are final if they are sold to the final (end) user. Goods and services are intermediate if the purchaser is not the final user. If you buy a car from a dealer, the car is a final good. If an automobile manufacturer buys steel from a steel foundry, that steel is an intermediate good. 
3.	Gross domestic product, or GDP, is the total value of all final goods and services produced in the economy during a given time period. 
4.	GDP is used as a measure of the size of an economy and can also be used to compare economic performance in other countries. 
5.	There are three ways to measure GDP: 
 - as the value of production of final goods and services. 
 - as aggregate spending (the sum of consumer spending, investment spending, government purchases, and exports minus imports) on domestically produced final goods and services. 
 - as factor income earned by households from firms in the economy. 
6.	It doesn’t matter if we add up all the spending or all the incomes because one person’s spending is another person’s income. 

##	Measuring GDP as the value of production of final goods and services 
1.	GDP is calculated by summing the value of all final goods and services produced in an economy in a given year. 
2.	The value of intermediate goods is omitted from this calculation of GDP. If the value of intermediate goods is included, this would result in double-counting. For example, the value of the steel produced that is used in an automobile is not counted in GDP since this is an intermediate good. 
3.	An alternative approach to computing GDP is to sum the value added by all firms (the value added is the difference between the value of its sales and the value of the intermediate goods and services it purchases from other businesses). 
4.	To avoid double-counting, only each producer’s value added is counted in the calculation of GDP. 

### Measuring GDP as spending on domestically produced final goods and services 
1.	GDP is calculated by summing spending on all final goods and services by all sectors of the economy. Spending by households (C), businesses (I), governments (G), and foreigners (X) is added together and spending on imports (IM) is subtracted. 
2.	Mathematically stated:

$$
\mathrm{GDP}=C+I+G+X-I M
$$

### Measuring GDP as factor income earned from firms in the economy 

1.	GDP is calculated by adding all of the income earned by factors of production from firms in the economy. This includes: 
  - wages earned by labor. 
  - interest earned by those who lend their savings to firms and the government. 
  - rent earned by those who lease their land or structures to firms. 
  - dividends paid to the shareholders.

In the breakdown of GDP by value added, the biggest component is the value added by businesses. In the breakdown of GDP by the four types of aggregate spending, consumer spending dominates overall spending. 

## Real GDP: A Measure of Aggregate Output 

The most important use of GDP is to measure the size of the economy. One must be careful when comparing economies over time because increases in GDP might represent increases in prices rather than increases in output. To measure changes in output, we need a modified version of GDP, known as real GDP.

A.	Aggregate output is the total quantity of final goods and services the economy produces. 
B.	Real GDP is the total value of all final goods and services produced in the economy during a given year, calculated using the prices of a selected base year. 
C.	Nominal GDP is the value of all final goods and services produced in the economy during a given year, calculated using the prices current in the year in which the output is produced. 
D.	To determine the actual growth in aggregate output, we calculate the change in real GDP using prices from some given base year, as in the following: 


$$
\text { Growth in real GDP }=\frac{\text { Real GDP in year } 2-\text { Real GDP in year } 1}{\text { Real GDP in year } 1}
$$


# Recitation

The following would  **Included in GDP** or Not Included in GDP in the US (i.e. the operation
would affect the value of GDP) ?

1.    **A restaurant makes a sandwich to sell to a customer**
2.    You make yourself a sandwich
3.    A pizza shop buys tomatoes to use to make pizza
4.    **A pizza shop buys an oven to use to make pizza**
5.    Toyota produces a car in Japan that is sold in the US.
6.    **Ford produces a car in the US that is sold in Japan.**
7.    **A house is built and sold this year in West LA.**
8.    A house is built in 1995 and sold this year in West LA.

## Question 1

Consider an Economy that produces only chocolate bars. In year 1 , they produce 3 bars at $\$ 4$ each, in year 2 , 4 bars at $\$ 5$, and in year 3, 5 bars at $\$ 6$. Year 1 is base year.

1.  What is nominal GDP for each year? Is this correctly calculated from revenue or expenditures?

2.  What is real GDP for each of these years?

3.  What is GDP deflator for each of these years?

4.  What is the percentage growth rate of real GDP from year 2 to $3 .$

5.  What is the inflation rate, as measured by GDP deflator from year 2 to 3 .

6.  Can you answer (e) and (e) without (b) and (c) (Hint, there's only one good)

**Answers**

1.  The value of nominal GDP is the market value of final goods, so we sum the value of goods produced (value = price per unit $\times$ quantity)

    So we have in year 1: $\$ 12$ ,in year 2 \$ 20, and in year 3: $\$ 30$.

2.  The value of real GDP is the market value of final goods where the prices of the good is the same as the base year (value = price per unit in base year $\times$ quantity)

    So we have in year 1: $\$ 12$ ,in year 2 \$ 16, and in year 3: $\$ 20$.

3.  The GDP deflator is calculated as the ratio of nominal to real GDP, since it the correction we do to account for the different prices

    So we have in year 1: 12/12 $\times$ 100 = 100 , in year 2 , 20/16 $\times$ 100 = 125 and in year 3 : 30/20 $\times$ 100 = 150

<!-- -->

4.  The growth in real GDP is calculated as the percentage change in two consecutive years, so we have that the percentage growth rate of real GDP from year 2 to $3 .(20-16) / 16 \times 100=25 \%$

5.  The inflation rate, as measured by GDP deflator from year 2 to 3 is:$(150-125) / 125 \times 100=20 \%$

6.  Yes, inflation can be measured with just price changes. This comes from the fact that there is only one good. Two or more goods, this is no longer true.

## Question 2

Calculating Nominal GDP, Real GDP, GDP growth rate, GDP Deflator and Inflation

| Year | Milk (P) |  Milk (Q)  | Honey (P) | Honey (Q)  |
|:----:|:--------:|:----------:|:---------:|:----------:|
| 2016 |   \$ 1   | 100 quarts |    \$2    | 50 quarts  |
| 2017 |   \$ 1   | 100 quarts |    \$2    | 100 quarts |
| 2018 |   \$ 2   | 100 quarts |    \$4    | 100 quarts |

**Answer:**

I choose the base year to be 2016:

| Year | NGPD = $\sum P \times Q$ |        RGDP        |      RGDP_gr       | GDP Defl.   | Inflation |
|------|:------------------------:|:------------------:|:------------------:|-------------|:---------:|
| 2016 |    1\*100+2\*50=\$200    | 1\*100+2\*50=\$200 |         \-         | 100         |    \-     |
| 2017 |    1\*100+2\*100=300     | 1\*100+2\*100=300  | (300-200)/200 = .5 | 100         |     0     |
| 2018 |    2\*100+4\*100=600     | 1\*100+2\*100=300  | (300-300)/300 = 0  | 600/3 = 200 |   100 %   |

## Question 3:

Suppose that people consume only three goods, as shown in this table :

|               | Tennis Balls | Golf Balls | Gatorade |
|:-------------:|:------------:|:----------:|:--------:|
|  2017 Price   |     \$2      |    \$4     |   \$1    |
| 2017 Quantity |     100      |    100     |   200    |
|  2018 Price   |     \$2      |    \$6     |   \$2    |
| 2018 Quantity |     100      |    100     |   200    |

1.  What is the percentage change in the price of each of the three goods?

2.  Using a method similar to the CPI, compute the percentage change in the overall price level. If you were to learn that a bottle of Gatorade increased in size from 2017 to 2018, should that information affect your calculation of the inflation rate? If so, how?

    **Answers:**

    1.  The percentage change in the price of each of the three goods:

        -   Tennis Balls : 0 %

        -   Golf Balls : 50 %

        -   Gatorade : 100 %

    2.  Here, since in the two years people are consuming the same amount of goods, the total amount of goods consumed can serve as the basket of goods for CPI:

        -   Total Cost in \$ {2017}=100 $\times$ 2+100 $\times$ 4+ 200$\times$ 1= 800\$

        -   Total Cost in \$ {2018}=100 $\times$ 2+100 $\times$ 6+ 200$\times$ 2= 1200\$

            Therefore, CPI using 2017 as the Base year would be

        -   CPI in \$ {2017}= $\frac{\text { TotalCost }_{2017}}{\text { TotalCost }_{2017}} \times 100=100$

        -   CPI in \$ {2018}= $\frac{\text { TotalCost }_{2018}}{\text { TotalCost }_{2017}} \times 100=150$

            And the percentage change in the overall price level :

        -   \% change =$\frac{C P I_{2018}-C P I_{2017}}{C P I_{2017}} \times 100=50 \%$

    If we find out that the size of a bottle of Gatorade had doubled in 2018 compared to 2017, then the increase in the price of Gatorade that we observe does not mean that Gatorade has become more expensive : it instead means that people consume more Gatorade than before. However, that effect is not taken into account when calculating Price level using CPI. Therefore compared to the inflation rate we get using CPI, the real inflation rate should be smaller.

## Question 4: Hands on students

Ask the students to fill the following table

| Year | Real GDP (Base Year 2000) | Nominal GDP | Deflator | Real GDP Growth Percent |
|:-----|:--------------------------|:------------|:---------|:------------------------|
| 1970 | 3000                      | 1200        | ?        | \-                      |
| 1980 | 5000                      | ?           | 60       | ?                       |
| 1990 | ?                         | 6000        | 100      | ?                       |
| 2000 | ?                         | ?           | ?        | 5                       |

Answer

| Year | Real GDP (Base Year 2000) | Nominal GDP       | Deflator          | Real GDP Growth Percent |
|:-----|:--------------------------|:------------------|:------------------|:------------------------|
| 1970 | 3000                      | 1200              | 1200/3000\*100=40 | \-                      |
| 1980 | 5000                      | 5000\*60/100=3000 | 60                | (5000-3000)/(3000)      |
| 1990 | 6000                      | 6000              | 100               | (6000-5000)/(5000)      |
| 2000 | 6000 \* 1.05=6300         | 6300              | 100               | 5                       |

Steps:

1.  Deflator in 1970, ratio of nominal to real GDP.

2.  Nominal GDP in 1980, real GDP\*GDP deflator/100

3.  Real GDP growth in 1980 and 1990,

    $$\frac{\text{real GDP} -  \text{real GDP previous period}}{\text{real GDP previous period}} \times 100$$

4.  In year 2000, GDP deflator in 100 base year, when the GDP deflator is 100:

    Nominal GDP = Real GDP.

5.  In year 2000, real GDP = real GDP in 1990 \* (1+Growth/100)

    $$\text{real GDP} = ( \text{real GDP previous period})\times (1+ \text{real GDP Growth}/ 100)$$

## Short Exercises

49. The table below contains data for the country of Togogo. The base year is $1974 .$

| Year | Nominal GDP | GDP Deflator |
|:----:|:-----------:|:------------:|
| 1974 |   \$2000    |     100      |
| 1975 |   \$3000    |     120      |
| 1976 |   \$3750    |     150      |
| 1977 |   \$6000    |     200      |

From 1975 to 1976,

<!-- -->

**a.  Inflation was $25 \%$ and output did not grow.**
b.  Inflation was $25 \%$ and output grew.
c.  Inflation was $50 \%$ and output did not grow.
d.  Inflation was $50 \%$ and output grew.


